apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: eizn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eizn
    app.kubernetes.io/part-of: byoc-app-whbj
  name: eizn
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: eizn
status:
  loadBalancer: {}
