apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: eizn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eizn
    app.kubernetes.io/part-of: byoc-app-whbj
  name: eizn
spec:
  rules:
  - host: eizn-byoc-lxma-tenant.apps.8fa8873ea7df9c02fe43.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: eizn
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
